version: '3.1'

services:
  redmine:
    image: redmine
    restart: always
    depends_on:
      - db
    links:
      - nginx
      - db
    environment:
      REDMINE_DB_MYSQL: db
      REDMINE_DB_USERNAME: redmine
      REDMINE_DB_PASSWORD: redmine
      REDMINE_DB_DATABASE: redmine
    volumes:
      - ./redmine/datadir:/usr/src/redmine/files
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER:  redmine
      MYSQL_DATABASE: redmine
      MYSQL_PASSWORD: redmine   
    ports:
      - 3306:3306
    volumes:
      - ./redmine/mysql/data:/var/lib/mysql
  nginx:
    image: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./redmine/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./redmine/nginx/logs:/var/log/nginx
      - ./redmine/letsencrypt/letsencrypt:/etc/letsencrypt
      - ./redmine/nginx/certs:/etc/nginx/certs
